# Μάθημα 2: Βασικά πακέτα - NumPy

## Τύποι δεδομένων και δομές δεδομένων:


Μάθαμε την προηγούμενη φορά τους τύπους δεδομένων:

• Integers: int( ) x = 8

• Float: float( ) x = 13.99

• Complex: x = 1a + 5d

• Bool: bool( ) x = False

• Strings: str( ) x = "Kalimera"

• Lists: list( ) x = [2, 98, 20, 32, -6, -21]

• Dictionaries: x = {"noumera": [98, 21], "thermokrasia": 9.3, "hlikia":15}


#### Νέοι τύποι δεδομένων:

• Numpy - Arrays:
    μοιάζουν με τις λίστες (lists)

• Panda - Dataframes:
    μοιάζουν με αρχεία του excel

### Πακέτα NumPy & Numpy Arrays

![Image of operators](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png)

#### The NumPy package

To Numpy υποστηρίζει μεγάλα, πολλών διαστάσεων διανύσματα και πίνακες στην Python, μαζί με μια συλλογή από σημαντικές μαθηματικές συναρτήσεις που χρειάζονται για τους υπολογισμούς των πινάκων αυτών (γραμμική άλγεβρα κ.λπ.).

#### Numpy Arrays

Κυρίως σε συνδυασμό με άλλα πακέτα το NumPy δημιουργεί μια νέα δομή την array, η οποία δίνει τη δυνατότητα να ορισθούν διανύσματα και πίνακες. Το array είναι μια δομή που μοιάζει με τη δομή list της Python. Σε αντίθεση με τη list η διάσταση ενός array είναι ορισμένη από την αρχή και αποθηκεύει αντικείμενα που είναι μόνο του ίδου τύπου (δηλαδή int, float, boolean, str, ...)

Άρα το κυρίως αντικείμενο του Numpy είναι ένα ομογενές διάστημα πολλών διαστάσεων και στην ουσία είναι ένας πίνακας στοιχείων, συνήθως αριθμών, του ίδιου τύπου. Οι διαστάσεις ονομάζονται axes. Όπως και στις λίστες για να καλέσουμε ένα np.array χρησιμοποιούμε τις παρενθέσεις. 

    Το Index ξεκινά από το 0.

    Με την εντολή array([1, 2, 3]) δημιουργούμε ένα αντικείμενο array που έχει διάσταση 1.

    Είναι το διάνυσμα [1, 2, 3].

*Παράδειγμα:*

In [49]:
import numpy as np

array_1 = np.array( [1, 2, 3] ) 
#για να καλέσουμε ένα στοιχείο: 
x = array_1 [0]
x 

1

Όπως είδατε παραπάνω πρώτα πρέπει να καλέσουμε το πακέτο με το **import numpy as np**

(αν δουλεύαμε τοπικά τότε πρώτα θα έπρεπε να εγκαταστήσουμε το πακέτο **με pip3 install numpy**  (στο terminal) και μετά να το καλέσουμε μέσα στο περιβάλλον εργασίας μας).


Όπως και στις λίστες, υπάρχουν διάφορες εντολές οι οποίες μας δίνουν πληροφορίες για ένα αντικείμενο array. 
Το ndim επιστρέφει τη διάσταση του array , η shape τη μορφή και η dtype το είδος
των στοιχείων του array.

In [50]:
#διάσταση
print(array_1 .ndim)
#τύπος
print(type(array_1 ))
#μορφή
print(array_1 .shape)

1
<class 'numpy.ndarray'>
(3,)


Τα μονοδιάστατα arrays μπορούν να ταξινομηθούν, να κομματιαστούν κ.λπ. όπως ακριβώς και οι λίστες στην 
Python.

*Παράδειγμα:* 1D

In [52]:
data = np.array([8, 5, 67, -15])
data[0] # το indexing επιστρέφει 8
data[2] # το indexing επιστρέφει  67
data[2: ] # το slicing επιστρέφει ένα νέο array – επιστρέφει : 67, -15
data[:2 ] # το slicing  επιστρέφει ένα νέο  array – επιστρέφει : 8, 5

array([8, 5])

In [26]:
e =np.array([1,2,3,4,5])
print(e[0:4])

[1 2 3 4]


Τα πολυδιάστατα arrays μπορούν να έχουν ένα index ανά axis. 
Αυτοί οι αριθμοί δίνονται σε ένα tuple (πλειάδα) που χωρίζεται με κόμματα.

*Παράδειγμα:* 2D   (2-διάστατο (μορφή πίνακα) array)

In [53]:
data2D = np.array( [[5, 6, -3] , [1, -3, -14]] )

Σε ένα πολυδιάστατο array πρέπει να ορίσουμε το κομμάτιασμα σε κάθε διάσταση,

δηλαδή data2D[rows, columns ]


In [54]:
data2D[:2, 0 ] # επιστρέφει ένα νέο array

array([5, 1])

In [55]:
a=np.array([[1,2,5],[3,4,6],[5,6,8]])

In [56]:
print(a[:,1]) # δεύτερη στήλη

[2 4 6]


In [57]:
print(a[0:2,:]) # δυο πρώτες γραμμές

[[1 2 5]
 [3 4 6]]


In [58]:
print(a[1:,1:]) # κάτω δεξια υποπίνακας

[[4 6]
 [6 8]]


#### Πράξεις 


Τα διαστήματα διαφέρουν από τις λίστες και γιαυτό στο σημείο αυτό χρειάζεται λίγη προσοχή. 

Το αποτέλεσμα κάθε πράξης αποθηκεύεται σε ένα **νέο** array.

In [61]:
my_data = np.array( [2, 4, 7, 9] )

In [63]:
my_data + [4, 2, -1, 3]

array([ 6,  6,  6, 12])

Ενώ η λίστα στο παραπάνω παράδειγμα θα επέστρεφε: [2, 4, 7, 9, 4, 2, -1, 3]

In [64]:
my_data * 2

array([ 4,  8, 14, 18])

Ενώ η λίστα στο παραπάνω παράδειγμα θα επέστρεφε: [2, 4, 7, 9, 2, 4, 7, 9]

### Ένωση arrays:

Προσοχή: Οι διαστάσεις των input arrays πρέπει να ταιριάζουν ακριβώς!

*Παράδειγμα:* np.concatenate((data1, data2), axis=0)

Με τον καθορισμό του **axis** με το οποίο θα γίνει η ένωση λέμε στην   Python πώς θέλουμε να ενώσει τα 2 διαστήματα, κάθετα ή οριζόντια:

    •  axis= 0 -- > για κάθε column

    •  axis= 1 -- > για κάθε row

#### Πρόσθεση / Αφαίρεση στοιχείων:
    •  np.insert(data, 1,5) πρόσθεση στοιχείων στο array

    •  np.delete(data, [1]) αφαίρεση στοιχείων από το array

#### Μαθηματικές λειτουργίες:

    • my_array.shape διαστάσεις του my_array 

    • np.mean(variable) το mean του array

    • np.median(variable) το median του array

    • np.std(variable) το standard deviation του array

#### Γραμμική Άλγεβρα

• Μετατόπιση (Transposing): np.transpose(data) 

Μετατρέπει τις διαστάσεις του array, (από οριζόντια διάταση, θα έχουν κάθετη διάταξη μετά την μετατόπιση, φανταστείτε σε ένα excel τις γραμμές να μετατρέπονται σε στήλες και το αντίθετο). 


In [44]:
a = np.array ( [[1, 2, 3], [3, 4, 6.7], [5, 9.0, 5]] )

a.transpose() 

array([[1. , 3. , 5. ],
       [2. , 4. , 9. ],
       [3. , 6.7, 5. ]])

#### Δουλέυοντας με τυχαίους αριθμούς:

In [45]:
np.random.random((2,2)) #δημιουργεί ένα array με τυχαίους αριθμούς

array([[0.28950629, 0.04544329],
       [0.39617448, 0.6023448 ]])

In [48]:
#np.random.randn(rows, columns) δημιουργεί ένα array με τυχαίους κανονικά κατανεμημένους αριθμούς 
random_numbers = np.random.randn(5,2)